### ISSUE TITLE
Is 'image' missing?

### ISSUE THREAD

**Issue by twopoint718** [alf-tool/alf#1]
When I try to run the following code

``` ruby
require 'alf'
require 'sqlite3'

rel = Alf.query('sap.sqlite3') do
  image(suppliers, supplies, :supplying)
end
```

I get the following error:

```
NoMethodError: undefined method `image' for Lispy([#<Module:0x000001013f69c8>]):#<Class:0x000001013f6180>
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/viewpoint.rb:60:in `method_missing'
    from (irb):24:in `block in irb_binding'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/lang/parser/lispy.rb:44:in `instance_exec'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/lang/parser/lispy.rb:44:in `evaluate'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/lang/parser/lispy.rb:28:in `parse'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/database/connection.rb:44:in `parse'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/database/connection.rb:48:in `optimize'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/database/connection.rb:52:in `relvar'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/database/connection.rb:56:in `query'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/facade.rb:14:in `block in query'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/database.rb:40:in `connect'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/database.rb:16:in `connect'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/facade.rb:9:in `connect'
    from /Users/chris/.rvm/gems/ruby-2.0.0-p353/gems/alf-core-0.15.0/lib/alf/facade.rb:13:in `query'
    from (irb):24
    from /Users/chris/.rvm/rubies/ruby-2.0.0-p353/bin/irb:12:in `<main>'
```

Thanks a lot! I have been enjoying reading about and using this gem so far.

**Comment by blambeau** [comment]
Hey,

Hmmm. The `image` relational operator just landed in Alf's master. try-alf.org should probably display the documentation of the last official version. I'll work on that as soon as I can. 

In the mean time, you might use a Gemfile to use the edge version of Alf. Also be aware that image has a rather naive implementation so far (have a look at the "physical" query plan)...

**Comment by blambeau** [comment]
Alf v0.16.0 has just been released. Image is included (but not optimized yet).

**Comment by twopoint718** [comment]
Thanks!
